name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
   # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "blog"
          commit_message: "Updated readme with the latest blog data"
          feed_list: https://blog.echosun.top/atom.xml
